apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.9.15-eclipse-temurin-21
      command:
        - cat
      tty: true
    - name: docker
      image: docker:29.4.0-cli
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock